### ISSUE TITLE
This repo is out of date

### ISSUE THREAD

**Issue by bitemyapp** [ua-parser/uap-haskell#1]
Newer commits here: https://github.com/tobie/ua-parser/tree/master/haskell

Here because of: https://github.com/tobie/ua-parser/blob/master/CONTRIBUTING.md

/cc @tobie @ozataman 

What's the current version of the Haskell library?

**Comment by ozataman** [comment]
This is the new repo, however I have not had the chance to port to this new structure. The old repo has a few bugfixes/maintenance commits on it, which is what's on Hackage currently.

**Comment by ozataman** [comment]
It's possible the adaptation is very minimal - haven't had much chance to investigate lately.

**Comment by bitemyapp** [comment]
@ozataman I'm going to update it. Would you update the cabal file on Hackage or consent to it being updated so the solver doesn't revert to 0.3 of the library?

**Comment by ozataman** [comment]
Sorry, I don't follow. The version I see on Hackage is 0.5; why would the
solver revert to 0.3? Is there an issue I am not aware of?

If the dependencies need updating, I'd be happy to do a 0.5.1 or similar
point release with the fix.

**Comment by bitemyapp** [comment]
http://hackage.haskell.org/package/ua-parser-0.3

There's no bounding on aeson, constraints that do not set a lower bound on ua-parser will jump to this version. This can be fixed without pushing a release.

The things I am doing to get uap-haskell in sync with uap-core are separate.

**Comment by qrilka** [comment]
@ozataman is this issue still valid? I see 0.7.1 version already
