### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by pbrisbin** [ua-parser/uap-haskell#10]
Hi there-

I rely on this package in bugsnag-haskell, which I was [trying to add to Stackage](https://github.com/commercialhaskell/stackage/pull/3871) but cannot because this package is not there. Would you be willing to add it to Stackage?

In my experience, the maintenance burden of being in Stackage is very low. If you're not willing, I can added it under my name, but I thought I'd try to get direct maintainer-ship for it first.

Thanks!

**Comment by MichaelXavier** [comment]
Submitted a PR: https://github.com/commercialhaskell/stackage/pull/3875

**Comment by mihaimaruseac** [comment]
Both merged, thanks
